--1
SELECT STUDENT_NAME AS "학생 이름"
     , STUDENT_ADDRESS AS "주소지"
  FROM TB_STUDENT
 ORDER BY STUDENT_NAME;
 
--2
SELECT STUDENT_NAME
     , STUDENT_SSN
  FROM TB_STUDENT
 WHERE ABSENCE_YN = 'Y'
 ORDER BY STUDENT_SSN DESC;
 
--3
SELECT STUDENT_NAME AS "학생이름"
     , STUDENT_NO AS "학번"
     , STUDENT_ADDRESS AS "거주지 주소"
  FROM TB_STUDENT
 WHERE SUBSTR(STUDENT_NO,1,1) = '9'
   AND SUBSTR(STUDENT_ADDRESS,1,3) IN ('강원도','경기도')
 ORDER BY STUDENT_NAME;
 
--4
SELECT PROFESSOR_NAME
     , PROFESSOR_SSN
  FROM TB_PROFESSOR
  JOIN TB_DEPARTMENT USING (DEPARTMENT_NO)
 WHERE DEPARTMENT_NAME = '법학과'
 ORDER BY PROFESSOR_SSN;
 
--5
SELECT S.*
  FROM (SELECT STUDENT_NO
             , POINT
          FROM TB_GRADE
         WHERE CLASS_NO = 'C3118100'
           AND TERM_NO = '200402'
         ORDER BY STUDENT_NO) S
 ORDER BY POINT DESC;
 
 
--6
SELECT STUDENT_NO
     , STUDENT_NAME
     , DEPARTMENT_NAME
  FROM TB_STUDENT A
     , TB_DEPARTMENT B
 WHERE A.DEPARTMENT_NO = B.DEPARTMENT_NO
 ORDER BY STUDENT_NAME ;
 
--7
SELECT CLASS_NAME
     , DEPARTMENT_NAME
  FROM TB_CLASS A
     , TB_DEPARTMENT B
 WHERE A.DEPARTMENT_NO = B.DEPARTMENT_NO;
 
--8
SELECT CLASS_NAME
     , PROFESSOR_NAME
  FROM TB_CLASS A
     , TB_PROFESSOR B
     , TB_CLASS_PROFESSOR C
 WHERE C.PROFESSOR_NO = B.PROFESSOR_NO
   AND A.CLASS_NO = C.CLASS_NO
 ORDER BY PROFESSOR_NAME;
 
 
 
 
 
  
     
