--1
SELECT STUDENT_NAME AS "학생 이름"
     , STUDENT_ADDRESS AS "주소지"
  FROM TB_STUDENT
 ORDER BY STUDENT_NAME;
 
--2
SELECT STUDENT_NAME
     , STUDENT_SSN
  FROM TB_STUDENT
 WHERE ABSENCE_YN = 'Y'
 ORDER BY STUDENT_SSN DESC;
 
--3
SELECT STUDENT_NAME AS "학생이름"
     , STUDENT_NO AS "학번"
     , STUDENT_ADDRESS AS "거주지 주소"
  FROM TB_STUDENT
 WHERE SUBSTR(STUDENT_NO,1,1) = '9'
   AND SUBSTR(STUDENT_ADDRESS,1,3) IN ('강원도','경기도')
 ORDER BY STUDENT_NAME;
 
--4
SELECT PROFESSOR_NAME
     , PROFESSOR_SSN
  FROM TB_PROFESSOR
  JOIN TB_DEPARTMENT USING (DEPARTMENT_NO)
 WHERE DEPARTMENT_NAME = '법학과'
 ORDER BY PROFESSOR_SSN;
 
--5
SELECT S.*
  FROM (SELECT STUDENT_NO
             , POINT
          FROM TB_GRADE
         WHERE CLASS_NO = 'C3118100'
           AND TERM_NO = '200402'
         ORDER BY STUDENT_NO) S
 ORDER BY POINT DESC;
 
 
--6
SELECT STUDENT_NO
     , STUDENT_NAME
     , DEPARTMENT_NAME
  FROM TB_STUDENT A
     , TB_DEPARTMENT B
 WHERE A.DEPARTMENT_NO = B.DEPARTMENT_NO
 ORDER BY STUDENT_NAME;
 
--7
SELECT CLASS_NAME
     , DEPARTMENT_NAME
  FROM TB_CLASS A
     , TB_DEPARTMENT B
 WHERE A.DEPARTMENT_NO = B.DEPARTMENT_NO;
 
--8
SELECT CLASS_NAME
     , PROFESSOR_NAME
  FROM TB_CLASS A
     , TB_PROFESSOR B
     , TB_CLASS_PROFESSOR C
 WHERE C.PROFESSOR_NO = B.PROFESSOR_NO
   AND A.CLASS_NO = C.CLASS_NO
 ORDER BY PROFESSOR_NAME;
 
--9
SELECT CLASS_NAME
     , PROFESSOR_NAME
  FROM TB_CLASS A
     , TB_PROFESSOR B
     , TB_CLASS_PROFESSOR C
     , TB_DEPARTMENT D
 WHERE C.PROFESSOR_NO = B.PROFESSOR_NO
   AND A.CLASS_NO = C.CLASS_NO
   AND D.DEPARTMENT_NO = A.DEPARTMENT_NO
   AND CATEGORY = '인문사회'
 ORDER BY PROFESSOR_NAME;
 
--10
SELECT S.STUDENT_NO AS "학번"
     , STUDENT_NAME AS "학생 이름"
     , G."전체 평점"
  FROM TB_STUDENT S
     , (SELECT STUDENT_NO 
             , ROUND(AVG(POINT),1) AS "전체 평점"
          FROM TB_GRADE
         GROUP BY STUDENT_NO) G
     , TB_DEPARTMENT D
 WHERE G.STUDENT_NO = S.STUDENT_NO
   AND D.DEPARTMENT_NO = S.DEPARTMENT_NO
   AND DEPARTMENT_NAME = '음악학과'
 ORDER BY S.STUDENT_NO;

--11
SELECT DEPARTMENT_NAME AS "학과이름"
     , STUDENT_NAME AS "학생이름"
     , PROFESSOR_NAME AS "지도교수이름"
  FROM TB_DEPARTMENT D
     , TB_STUDENT S
     , TB_PROFESSOR P
 WHERE D.DEPARTMENT_NO = S.DEPARTMENT_NO
   AND S.COACH_PROFESSOR_NO = P.PROFESSOR_NO
   AND STUDENT_NO = 'A313047';

--12
SELECT STUDENT_NAME
     , TERM_NO AS "TERM_NAME"
  FROM TB_STUDENT S
     , TB_CLASS C
     , TB_GRADE G
 WHERE S.STUDENT_NO = G.STUDENT_NO
   AND C.CLASS_NO = G.CLASS_NO
   AND SUBSTR(TERM_NO,1,4) = '2007'
   AND CLASS_NAME ='인간관계론'
 ORDER BY STUDENT_NAME;
 
--13 CATEGORY = 예체능 , 담당교수 = NULL
SELECT CLASS_NAME
     , DEPARTMENT_NAME
  FROM TB_CLASS C
     , TB_DEPARTMENT D
     , TB_CLASS_PROFESSOR CP
 WHERE C.CLASS_NO = CP.CLASS_NO(+)
   AND C.DEPARTMENT_NO = D.DEPARTMENT_NO
   AND CATEGORY = '예체능'
   AND PROFESSOR_NO IS NULL
 ORDER BY DEPARTMENT_NAME;

--14
SELECT STUDENT_NAME AS "학생이름"
     , NVL(PROFESSOR_NAME, '지도교수 미지정') AS "지도교수"
  FROM TB_STUDENT S
     , TB_PROFESSOR P
     , TB_DEPARTMENT D
 WHERE S.COACH_PROFESSOR_NO = P.PROFESSOR_NO(+)
   AND S.DEPARTMENT_NO = D.DEPARTMENT_NO
   AND DEPARTMENT_NAME = '서반아어학과';

--15
SELECT S.STUDENT_NO AS "학번"
     , STUDENT_NAME AS "이름"
     , DEPARTMENT_NAME AS "학과 이름"
     , P.평점
  FROM TB_STUDENT S
     , TB_DEPARTMENT D
     , (SELECT STUDENT_NO
             , ROUND(AVG(POINT),8) AS "평점"
          FROM TB_GRADE
         GROUP BY STUDENT_NO
        HAVING AVG(POINT)>= 4) P
 WHERE S.STUDENT_NO = P.STUDENT_NO
   AND S.DEPARTMENT_NO = D.DEPARTMENT_NO
   AND ABSENCE_YN ='N'
 ORDER BY S.STUDENT_NO;

--16
SELECT C.CLASS_NO
     , CLASS_NAME
     , G."AVG(POINT)"
  FROM TB_CLASS C
     , (SELECT CLASS_NO
             , ROUND(AVG(POINT),8) AS "AVG(POINT)"
          FROM TB_GRADE
         GROUP BY CLASS_NO)G
     , TB_DEPARTMENT D
 WHERE C.DEPARTMENT_NO = D.DEPARTMENT_NO
   AND C.CLASS_NO = G.CLASS_NO
   AND DEPARTMENT_NAME ='환경조경학과'
   AND SUBSTR(CLASS_TYPE,1,2) = '전공'
 ORDER BY C.CLASS_NO;

--17
SELECT STUDENT_NAME
     , STUDENT_ADDRESS
  FROM TB_STUDENT 
 WHERE DEPARTMENT_NO = (SELECT DEPARTMENT_NO
                          FROM TB_STUDENT
                         WHERE STUDENT_NAME ='최경희'); 
                         
--18
--1) 국어국문학과에 속한 학생의 평점중 최대값
SELECT MAX(AVG(POINT)) 
  FROM TB_GRADE G
     , TB_STUDENT ST
     , TB_DEPARTMENT D
 WHERE G.STUDENT_NO = ST.STUDENT_NO
   AND ST.DEPARTMENT_NO = D.DEPARTMENT_NO
   AND DEPARTMENT_NAME = '국어국문학과'
 GROUP BY ST.STUDENT_NO;
 
--2)국어국문학과 다니는 학생들의 평점
SELECT S.STUDENT_NO
     , STUDENT_NAME 
     , AVG(POINT) 
  FROM TB_GRADE G
     , TB_STUDENT S
     , TB_DEPARTMENT D
 WHERE G.STUDENT_NO = S.STUDENT_NO
   AND S.DEPARTMENT_NO = D.DEPARTMENT_NO
   AND DEPARTMENT_NAME = '국어국문학과'
 GROUP BY STUDENT_NAME, S.STUDENT_NO
 ORDER BY AVG(POINT) DESC;
 
--3) 국어국문학과 학생중 평점이 최대값과 같은 학생
SELECT S.STUDENT_NO
     , S.STUDENT_NAME 
  FROM TB_GRADE G
     , TB_STUDENT S
     , TB_DEPARTMENT D
 WHERE G.STUDENT_NO = S.STUDENT_NO
   AND S.DEPARTMENT_NO = D.DEPARTMENT_NO
   AND DEPARTMENT_NAME = '국어국문학과'
 GROUP BY S.STUDENT_NAME, S.STUDENT_NO
HAVING AVG(POINT) = (SELECT MAX(AVG(POINT)) 
                       FROM TB_GRADE G
                          , TB_STUDENT ST
                          , TB_DEPARTMENT D
                      WHERE G.STUDENT_NO = ST.STUDENT_NO
                        AND ST.DEPARTMENT_NO = D.DEPARTMENT_NO
                        AND DEPARTMENT_NAME = '국어국문학과'
                      GROUP BY ST.STUDENT_NO);
                      
--4)ROWNUM 이용
SELECT STUDENT_NO
     , STUDENT_NAME
  FROM (SELECT S.STUDENT_NO AS STUDENT_NO
             , STUDENT_NAME 
             , AVG(POINT) 
          FROM TB_GRADE G
             , TB_STUDENT S
             , TB_DEPARTMENT D
         WHERE G.STUDENT_NO = S.STUDENT_NO
           AND S.DEPARTMENT_NO = D.DEPARTMENT_NO
           AND DEPARTMENT_NAME = '국어국문학과'
         GROUP BY STUDENT_NAME, S.STUDENT_NO
         ORDER BY AVG(POINT) DESC)
 WHERE ROWNUM = 1;

--19
-- 1) 학과별 전공평점
SELECT DEPARTMENT_NO
     , AVG(POINT)
  FROM TB_STUDENT 
  JOIN TB_GRADE USING (STUDENT_NO)
  JOIN TB_CLASS USING (DEPARTMENT_NO)
 WHERE SUBSTR(CLASS_TYPE,1,2) = '전공'
 GROUP BY DEPARTMENT_NO;

    
--2) "환경조경학과"가 속한 같은 계열 학과
SELECT DEPARTMENT_NO
  FROM TB_DEPARTMENT
 WHERE CATEGORY =  (SELECT CATEGORY
                      FROM TB_DEPARTMENT
                     WHERE DEPARTMENT_NAME = '환경조경학과'); 
     
--3) 학과별 전공 평점 중 환경조경학과가 속한 같은 계열의 학과인것

SELECT DEPARTMENT_NAME AS "계열 학과명"
     , ROUND(AVG(POINT),1) AS "전공평점"
  FROM TB_STUDENT 
  JOIN TB_GRADE USING (STUDENT_NO)
  JOIN TB_DEPARTMENT USING(DEPARTMENT_NO)
  JOIN TB_CLASS USING (DEPARTMENT_NO)
 WHERE SUBSTR(CLASS_TYPE,1,2) = '전공'
   AND DEPARTMENT_NAME IN (SELECT DEPARTMENT_NAME
                             FROM TB_DEPARTMENT
                            WHERE CATEGORY =  (SELECT CATEGORY
                                                 FROM TB_DEPARTMENT
                                                WHERE DEPARTMENT_NAME = '환경조경학과'))
 GROUP BY DEPARTMENT_NAME
 ORDER BY DEPARTMENT_NAME;
 
 

  
     
