--1
SELECT STUDENT_NO   AS 학번,
       STUDENT_NAME AS 이름,
       TO_CHAR(ENTRANCE_DATE,'YYYY-MM-DD') AS 입학년도 --포맷바꾸기
  FROM TB_STUDENT
 WHERE DEPARTMENT_NO = '002'
 ORDER BY ENTRANCE_DATE;
 
--2
SELECT PROFESSOR_NAME,
       PROFESSOR_SSN
  FROM TB_PROFESSOR
 WHERE PROFESSOR_NAME NOT LIKE '___';
 
--3
SELECT PROFESSOR_NAME AS 교수이름,
       TO_CHAR(SYSDATE,'YYYY')-('19'||SUBSTR(PROFESSOR_SSN,1,2)) AS 나이
  FROM TB_PROFESSOR
 WHERE SUBSTR(PROFESSOR_SSN,8,1) = 1
 ORDER  BY 나이;  
       
--4
SELECT SUBSTR(PROFESSOR_NAME,2) AS 이름
  FROM TB_PROFESSOR;

--5
SELECT STUDENT_NO,
       STUDENT_NAME
  FROM TB_STUDENT
 WHERE TO_CHAR(ENTRANCE_DATE,'YYYY')-('19'||SUBSTR(STUDENT_SSN,1,2)) > 19;

--6
SELECT TO_CHAR(TO_DATE('20/12/25','YY/MM/DD'),'DAY')
  FROM DUAL;

 
--7 YY는 무조건 2000년대, RR은 50기준 미만 : 2000년대, 이상 : 1900년대
SELECT TO_DATE('99/10/11','YY/MM/DD'),
       TO_DATE('49/10/11','YY/MM/DD'),
       TO_DATE('99/10/11','RR/MM/DD'),
       TO_DATE('49/10/11','RR/MM/DD')
  FROM DUAL;
  
--8
SELECT STUDENT_NO,
       STUDENT_NAME
  FROM TB_STUDENT
 WHERE SUBSTR(STUDENT_NO,1,1) <> 'A';
 
--9
SELECT ROUND(AVG(POINT),1) AS 평점
  FROM TB_GRADE
 WHERE STUDENT_NO ='A517178';
 
--10
SELECT DEPARTMENT_NO AS 학과번호,
       COUNT(*)      AS "학생수(명)"
  FROM TB_STUDENT
 GROUP BY DEPARTMENT_NO
 ORDER BY DEPARTMENT_NO;
 
--11 
SELECT COUNT(*)
  FROM TB_STUDENT
 WHERE COACH_PROFESSOR_NO IS NULL;

--12
SELECT DISTINCT SUBSTR(TERM_NO,1,4) AS "년도",
       ROUND(AVG(POINT),1)          AS "년도 별 평점"
  FROM TB_GRADE
 WHERE STUDENT_NO = 'A112113'
 GROUP BY SUBSTR(TERM_NO,1,4)
 ORDER BY SUBSTR(TERM_NO,1,4);
 
--13
SELECT DEPARTMENT_NO AS 학과코드명,
       COUNT(*)      AS "휴학생 수"
  FROM TB_STUDENT
 WHERE ABSENCE_YN = 'Y'
 GROUP BY DEPARTMENT_NO
 ORDER BY DEPARTMENT_NO;
 
--14 
SELECT STUDENT_NAME        AS "동일이름",
       COUNT(STUDENT_NAME) AS "동명인 수"
  FROM TB_STUDENT
 GROUP BY STUDENT_NAME
HAVING COUNT(STUDENT_NAME) > 1
 ORDER BY STUDENT_NAME;
 
--15
/*
SELECT SUBSTR(TERM_NO,1,4) AS "년도",
       DECODE(SUBSTR(TERM_NO,6),'1','01','2','02','3','  '),
       AVG(POINT)
  FROM TB_GRADE
 WHERE STUDENT_NO = 'A112113'
 GROUP BY SUBSTR(TERM_NO,6);
*/
       

